<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vsoevvscout"
 *
 * Auto generated by Extension Builder 2014-01-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'ÖVV Scout',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Berti Golf',
	'author_email' => 'info@berti-golf.de',
	'author_company' => 'volleybalserver.de',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>